### ISSUE TITLE
web.QA.config not showing up

### ISSUE THREAD

**Issue by sayedihashimi** [sayedihashimi/package-web#11]
For some reason if a file is named web.QA.config it doesn't show up as an available transform when publishing.

This is most likely related to the regex used to pick up the config transforms.

**Comment by sayedihashimi** [comment]
Should be fixed now

**Comment by timmi4sa** [comment]
Hi Sayed, what a wonderful initiative (It's like nobody at Microsoft (except you and Mr. Hanselman) were thinking about the `real` lifecycle the developers are following). 

I saw that this was fixed 4 months ago, but was the fix published as NuGet? The reason I am asking is that I installed the NuGet on 06/20/2013 (yesterday) and still experience the `QA`-missing issue. Thank you for the clarification on this!

My environment: VS2010 SP1 with Web Deployment Update (so the Publish wizard now looks like VS2012).
